
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.awt.print.*;
import java.io.File;
import java.io.IOException;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinayak
 */
public class SavedTimeTableDisplayer extends javax.swing.JFrame {

    /**
     * Creates new form SavedTimeTableDisplayer
     */
    public SavedTimeTableDisplayer() {
        initComponents();
        
        //For some table stuff
        DefaultTableCellRenderer c = new DefaultTableCellRenderer();
            c.setHorizontalAlignment(SwingConstants.CENTER);

            for(int co=0; co<9; co++)
            {
                tTable.getColumnModel().getColumn(co).setCellRenderer(c);
            }
         
        TableCellRenderer rendererFromHeader = tTable.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        
        tTable.setShowGrid(true);
        tTable.setShowVerticalLines(true);
        
        //For displaying the fixed values
        tTable.setValueAt("Monday",0,0);
        tTable.setValueAt("Tuesday",1,0);
        tTable.setValueAt("Wednesday",2,0);
        tTable.setValueAt("Thursday",3,0);
        tTable.setValueAt("Friday",4,0);
        tTable.setValueAt("Saturday",5,0);
        tTable.setValueAt("L",0,5);
        tTable.setValueAt("U",1,5);
        tTable.setValueAt("N",2,5);
        tTable.setValueAt("C",3,5);
        tTable.setValueAt("H",4,5);
        tTable.setValueAt("BREAK",5,5);
        
        //For displaying the time table fetched frome the database
        for(int i=0; i<6; i++){
            for(int j=0; j<4; j++){
                tTable.setValueAt(SavedTimeTable.producedTimeTable[i][j], i, j+1);
            }
        }
        
        for(int i=0; i<6; i++){
            for(int j=4; j<7; j++){
                tTable.setValueAt(SavedTimeTable.producedTimeTable[i][j], i, j+2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tTable = new javax.swing.JTable();
        download = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Time Table");

        tTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tTable.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Day", "Period 1", "Period 2", "Period 3", "Period 4", "LUNCH", "Period 5", "Period 6", "Period 7"
            }
        ));
        tTable.setEnabled(false);
        tTable.setPreferredSize(new java.awt.Dimension(1775, 360));
        tTable.setRequestFocusEnabled(false);
        tTable.setRowHeight(60);
        tTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tTable);

        download.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        download.setText("Download");
        download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(871, 871, 871)
                .addComponent(download)
                .addContainerGap(860, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(download)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadActionPerformed
        String h="Sem: " + SavedTimeTable.semester + "   Branch: " + SavedTimeTable.branch + "   Section: " +SavedTimeTable.section;
        MessageFormat header = new MessageFormat(h);
        MessageFormat footer = new MessageFormat("Created by Vinayak");
        String tableName=SavedTimeTable.semester + SavedTimeTable.branch + SavedTimeTable.section;
        try {
            JScrollPane scroll = new JScrollPane(tTable);

            scroll.setColumnHeaderView(tTable.getTableHeader());
            tTable.setPreferredScrollableViewportSize(tTable.getPreferredSize());

            JPanel p = new JPanel(new BorderLayout());
            p.add(scroll, BorderLayout.CENTER);

            BufferedImage bi = ScreenImage.createImage(p);

            this.setVisible(false);
            JOptionPane.showMessageDialog(null, new JLabel(new ImageIcon(bi)));
            ImageIO.write(bi,"png",new File("C:\\Users\\vinay\\Desktop\\"+ tableName +".png"));
            JOptionPane.showMessageDialog(null, "Saved to desktop with name "+tableName, "Successfully saved", JOptionPane.ERROR_MESSAGE);
//            tTable.print(JTable.PrintMode.NORMAL, header, footer);
//        } catch (PrinterException ex) {
//            Logger.getLogger(SavedTimeTableDisplayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SavedTimeTableDisplayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_downloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SavedTimeTableDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SavedTimeTableDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SavedTimeTableDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SavedTimeTableDisplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SavedTimeTableDisplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton download;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tTable;
    // End of variables declaration//GEN-END:variables
}
