
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class second extends javax.swing.JFrame {

    /**
     * Creates new form second
     */
    public second() {
        initComponents();
    }
    
    static int[][] TT = new int[6][7];
    //FOR CHANGE
        static int change=0;
    //FOR CHANGE

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        ss1 = new javax.swing.JLabel();
        ss2 = new javax.swing.JLabel();
        ss3 = new javax.swing.JLabel();
        ss4 = new javax.swing.JLabel();
        ss5 = new javax.swing.JLabel();
        ss6 = new javax.swing.JLabel();
        ss7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        te1 = new javax.swing.JTextField();
        te2 = new javax.swing.JTextField();
        te3 = new javax.swing.JTextField();
        te4 = new javax.swing.JTextField();
        te5 = new javax.swing.JTextField();
        te6 = new javax.swing.JTextField();
        te7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        jLabel1.setText("Section");

        ss1.setBackground(new java.awt.Color(255, 102, 102));
        ss1.setText("asdff");

        ss2.setText("jLabel3");

        ss3.setText("jLabel4");

        ss4.setText("jLabel5");

        ss5.setText("jLabel6");

        ss6.setText("jLabel7");

        ss7.setText("jLabel8");

        jLabel9.setText("Teacher-Name");

        te1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te1ActionPerformed(evt);
            }
        });

        te3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te3ActionPerformed(evt);
            }
        });

        te7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te7ActionPerformed(evt);
            }
        });

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ss1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(te6, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(te5)
                            .addComponent(te4)
                            .addComponent(te3)
                            .addComponent(te2)
                            .addComponent(te1)
                            .addComponent(te7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ss2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ss3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ss7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addComponent(ss6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ss5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ss4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ss1)
                    .addComponent(te1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss2)
                    .addComponent(te2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss3)
                    .addComponent(te3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss4)
                    .addComponent(te4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ss5)
                    .addComponent(te5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ss6)
                    .addComponent(te6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ss7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(te7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        ss2.getAccessibleContext().setAccessibleName("j3");
        ss3.getAccessibleContext().setAccessibleName("");
        ss4.getAccessibleContext().setAccessibleName("j5");
        ss5.getAccessibleContext().setAccessibleName("");
        ss6.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[][] periods = new int[7][3];
        //FOR CHANGE
            
            for(int i=0; i<5; i++){
                if(NewJFrame.subject[i][2]==0){
                    change=i;
                    NewJFrame.subject[i][2]=1;
                    NewJFrame.list1.add(Integer.toString(i)+"2");
                    break;
                }
            }
        //FOR CHANGE
        for(int i=0; i<7; i++)
        {
          if(NewJFrame.subject[i][0]==1)
          {
              periods[i][0]=5;
          }
          if(NewJFrame.subject[i][1]==1)
          {
              if(NewJFrame.subject[i][0]==1)
              {
                  periods[i][1]=2;
              }
              else
              {
                  periods[i][1]=4;
              }
          }
          if(NewJFrame.subject[i][2]==1)
          {
              periods[i][2]=1;
          }
        }

        Random random = new Random();
        System.out.print(NewJFrame.list1.toString());

        //ArrayList<String> list1 = new ArrayList<String>(
        //Arrays.asList("00","01","02","10","11","12","20","22","30","32","40","42","51","61"));

        for(int i=0; i<6; i++)
        {
              ArrayList<String> list = new ArrayList<String>();
              int counter=0;
              for(int j=0; j<7; j++)
              {
                      int x,y,flag=1;
                      String r="";
                      do
                      {
                          flag=1;
                          //x=random.nextInt(7);

                          if(counter==0 && (j!=1 && j!=3 && j!=4 && j!=6))
                          {                                       //Anthing can come here as there is no boundation that the practical could not appear here.
                              int randomNumber=random.nextInt(NewJFrame.list1.size());
                              r=NewJFrame.list1.get(randomNumber);
                          }
                          else
                          {
                              do                                  //This is loop to ensure that here come the theory or tutorial only
                              {
                                  int randomNumber=random.nextInt(NewJFrame.list1.size());
                                  r=NewJFrame.list1.get(randomNumber);
                                  System.out.println("hey  i am r "+ r);
                                  y=Integer.parseInt(String.valueOf(r.charAt(1)));
                              }while(y==1);
                          }

                          if(list.size()!=0)
                          {
                              if(list.indexOf(r)!=-1)
                              {
                                  flag=0;                       //for not adding the subject which is already added for that day
                              }
                              for(int l=0;l<list.size();l++)
                              {
                                  Character c=new Character(list.get(l).charAt(0));
                                  Character d=new Character(list.get(l).charAt(1));
                                  //if(r.charAt(1)!=1)
                                  //{ 
                                  //Below code for ensuring that in a single day no two practical can come
                                  
                                      if(c.equals(new Character(r.charAt(0))) && !((new Character(r.charAt(1)).equals(new Character('1'))) || d.equals(new Character('1'))))
                                      {
                                          flag=0;
                                          break;
                                      }
                                  //}
                              }
                          }

                      x=Integer.parseInt(String.valueOf(r.charAt(0)));
                      y=Integer.parseInt(String.valueOf(r.charAt(1)));

                      }while(periods[x][y]<=0 || flag==0);         //if there is no period available for the randoml selected subject then the do the whole thing again


                      if(y==1)
                      {
                              TT[i][j]=TT[i][j+1]=Integer.parseInt(r);   
                              j+=1;
                              periods[x][y]-=2;
                              counter=1;
                      }
                      else
                      {
                              TT[i][j]=Integer.parseInt(r);
                              periods[x][y]-=1;
                      }

                      list.add(r);

                      if(periods[x][y]==0){
                          NewJFrame.list1.remove(new String(r));
                      }
                          
                      //for checking
                      for(int k=0; k<7; k++)
                      {
                          System.out.print(periods[k][0]);
                          System.out.print(periods[k][1]);
                          System.out.println(periods[k][2]);
                      }
                      System.out.println(list.toString());
                      System.out.println(NewJFrame.list1.toString());
                      //for checking

              }
              list.removeAll(list);
              System.out.println("");
              System.out.println("");
        }
        //just for checking
        for(int i=0; i<6; i++){
            for(int j=0; j<7; j++){
                System.out.print(TT[i][j]+" ");
            }
            System.out.println("");
        }
        //for checking
  
        Timetable s1=new Timetable();
        s1.setVisible(true);
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void te1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_te1ActionPerformed

    private void te3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_te3ActionPerformed

    private void te7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_te7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new second().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel ss1;
    public javax.swing.JLabel ss2;
    public javax.swing.JLabel ss3;
    public javax.swing.JLabel ss4;
    public javax.swing.JLabel ss5;
    public javax.swing.JLabel ss6;
    public javax.swing.JLabel ss7;
    private javax.swing.JTextField te1;
    private javax.swing.JTextField te2;
    private javax.swing.JTextField te3;
    private javax.swing.JTextField te4;
    private javax.swing.JTextField te5;
    private javax.swing.JTextField te6;
    private javax.swing.JTextField te7;
    // End of variables declaration//GEN-END:variables
}
